service: helloworld
frameworkVersion: '3'
plugins:
  - serverless-offline
  - serverless-esbuild
custom:
  serverless-offline:
    httpPort: 5000
    noPrependStageInUrl: true
provider:
  name: aws
  runtime: nodejs20.x
  stage: ${opt:stage, 'development'}
  region: eu-west-3
  environment:
    STAGE: ${self:provider.stage}

functions:
  helloWorld:
    handler: src/grettings.handler
    events:
      - httpApi:
          method: GET
          path: /api/greetings
